// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AnimationController from "./animation_controller"
application.register("animation", AnimationController)

import DateOptionsController from "./date_options_controller"
application.register("date-options", DateOptionsController)

import DisplayDestinationController from "./display_destination_controller"
application.register("display-destination", DisplayDestinationController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ParticipationsController from "./participations_controller"
application.register("participations", ParticipationsController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)
