// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import DateOptionsController from "./date_options_controller";
application.register("date-options", DateOptionsController);

import ParticipationsController from "./participations_controller";
application.register("participations", ParticipationsController);

import FlatpickrController from "./flatpickr_controller";
application.register("flatpickr", FlatpickrController);

import HelloController from "./hello_controller";
application.register("hello", HelloController);
